- hosts: HK_FABRIC
  connection: local
  gather_facts: no
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: generate intented variables
      tags: [build]
      import_role:
         name: arista.avd.eos_designs

    - name: generate device intended config and documention
      tags: [build]
      import_role:
         name: arista.avd.eos_cli_config_gen
