---
- name: validate states on EOS devices
  hosts: HK_FABRIC
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd

  tasks:

    - name: validate states on EOS devices
      import_role:
        name: arista.avd.eos_validate_state