- name: Validate DC Fabric configuration with Batfish
  hosts: localhost
  connection: local
  roles:
    - batfish.base
  vars:
    snapshot: Arista_HK_Config
    network: Arista_HK
    
  tasks:

    - name: Pre Deployment fabric validation
      import_role:
         name: eos_pre_fabric_validation